a = int(input("Enter a number greater than 0: "))
b = int(input("Enter second number greater than 0: "))
print(f"Addition: {a + b}")
print(f"Subtraction: {a - b}")
print(f"Division: {a / b}")
print(f"Multiplication: {a * b}")
